/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiWalletSol from "./MultiWallet.sol";
export type { multiWalletSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { MultiSigWallet } from "./MultiWallet.sol/MultiSigWallet";
export { MultiSigWallet__factory } from "./factories/MultiWallet.sol/MultiSigWallet__factory";
