/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from "./IERC20__factory";
export { Lock__factory } from "./Lock__factory";
export { StakingContract__factory } from "./StakingContract__factory";
export { StakingFactory__factory } from "./StakingFactory__factory";
export { TokenA__factory } from "./TokenA__factory";
export { TokenB__factory } from "./TokenB__factory";
