const customeTheme = {
  "--ck-font-family": "Inter",
  "--ck-font-weight": "400",
  "--ck-border-radius": "var(--radius-xl)",
  "--ck-overlay-backdrop-filter": "blur(0px)",
  "--ck-modal-heading-font-weight": "500",
  "--ck-qr-border-radius": "var(--radius-lg)",

  "--ck-connectbutton-font-size": "15px",
  "--ck-connectbutton-color": "var(--foreground)",
  "--ck-connectbutton-background": "var(--secondary)",
  "--ck-connectbutton-background-secondary": "var(--background)",
  "--ck-connectbutton-border-radius": "var(--radius-lg)",
  "--ck-connectbutton-box-shadow": "0 0 0 0 transparent",
  "--ck-connectbutton-hover-color": "var(--foreground)",
  "--ck-connectbutton-hover-background": "var(--muted)",
  "--ck-connectbutton-hover-box-shadow": "0 0 0 0 transparent",
  "--ck-connectbutton-active-color": "var(--foreground)",
  "--ck-connectbutton-active-background": "var(--accent)",
  "--ck-connectbutton-active-box-shadow": "0 0 0 0 transparent",
  "--ck-connectbutton-balance-color": "var(--foreground)",
  "--ck-connectbutton-balance-background": "var(--background)",
  "--ck-connectbutton-balance-box-shadow": "inset 0 0 0 1px var(--border)",
  "--ck-connectbutton-balance-hover-background": "var(--secondary)",
  "--ck-connectbutton-balance-hover-box-shadow": "inset 0 0 0 1px var(--muted)",
  "--ck-connectbutton-balance-active-background": "var(--muted)",
  "--ck-connectbutton-balance-active-box-shadow":
    "inset 0 0 0 1px var(--border)",

  "--ck-primary-button-font-weight": "600",
  "--ck-primary-button-border-radius": "var(--radius-lg)",
  "--ck-primary-button-color": "var(--foreground)",
  "--ck-primary-button-background": "var(--secondary)",
  "--ck-primary-button-box-shadow": "0 0 0 0 transparent",
  "--ck-primary-button-hover-color": "var(--foreground)",
  "--ck-primary-button-hover-background": "var(--muted)",
  "--ck-primary-button-hover-box-shadow": "0 0 0 0 transparent",
  "--ck-primary-button-active-color": "var(--foreground)",
  "--ck-primary-button-active-background": "var(--accent)",
  "--ck-primary-button-active-box-shadow": "0 0 0 0 transparent",

  "--ck-secondary-button-font-weight": "500",
  "--ck-secondary-button-border-radius": "var(--radius-lg)",
  "--ck-secondary-button-color": "var(--foreground)",
  "--ck-secondary-button-background": "var(--secondary)",
  "--ck-secondary-button-box-shadow": "0 0 0 0 transparent",
  "--ck-secondary-button-hover-color": "var(--foreground)",
  "--ck-secondary-button-hover-background": "var(--muted)",
  "--ck-secondary-button-hover-box-shadow": "0 0 0 0 transparent",
  "--ck-secondary-button-active-color": "var(--foreground)",
  "--ck-secondary-button-active-background": "var(--accent)",
  "--ck-secondary-button-active-box-shadow": "0 0 0 0 transparent",

  "--ck-tertiary-button-font-weight": "500",
  "--ck-tertiary-button-border-radius": "var(--radius-lg)",
  "--ck-tertiary-button-color": "var(--foreground)",
  "--ck-tertiary-button-background": "var(--secondary)",
  "--ck-tertiary-button-box-shadow": "0 0 0 0 transparent",
  "--ck-tertiary-button-hover-color": "var(--foreground)",
  "--ck-tertiary-button-hover-background": "var(--muted)",
  "--ck-tertiary-button-hover-box-shadow": "0 0 0 0 transparent",
  "--ck-tertiary-button-active-color": "var(--foreground)",
  "--ck-tertiary-button-active-background": "var(--accent)",
  "--ck-tertiary-button-active-box-shadow": "0 0 0 0 transparent",

  "--ck-modal-box-shadow": "0px 2px 4px 0px oklch(0 0 0 / 0.05)",
  "--ck-overlay-background": "oklch(0 0 0 / 0.08)",

  "--ck-body-color": "var(--foreground)",
  "--ck-body-color-muted": "var(--muted-foreground)",
  "--ck-body-color-muted-hover": "var(--primary)",
  "--ck-body-background": "var(--background)",
  "--ck-body-background-transparent": "transparent",
  "--ck-body-background-secondary": "var(--secondary)",
  "--ck-body-background-secondary-hover-background": "var(--muted)",
  "--ck-body-background-secondary-hover-outline": "var(--ring)",
  "--ck-body-background-tertiary": "var(--accent)",
  "--ck-body-action-color": "var(--muted-foreground)",
  "--ck-body-divider": "var(--border)",
  "--ck-body-color-danger": "var(--destructive)",
  "--ck-body-color-valid": "var(--chart-5)",
  "--ck-siwe-border": "var(--border)",
  "--ck-body-disclaimer-background": "var(--secondary)",
  "--ck-body-disclaimer-color": "var(--muted-foreground)",
  "--ck-body-disclaimer-link-color": "var(--accent-foreground)",
  "--ck-body-disclaimer-link-hover-color": "var(--foreground)",

  "--ck-tooltip-background": "var(--background)",
  "--ck-tooltip-background-secondary": "var(--secondary)",
  "--ck-tooltip-color": "var(--muted-foreground)",
  "--ck-tooltip-shadow": "0px 2px 10px 0 oklch(0 0 0 / 0.14)",

  "--ck-dropdown-button-color": "var(--muted-foreground)",
  "--ck-dropdown-button-box-shadow":
    "0 0 0 1px var(--border), 0px 0px 7px oklch(0 0 0 / 0.05)",
  "--ck-dropdown-button-background": "var(--background)",
  "--ck-dropdown-button-hover-color": "var(--foreground)",
  "--ck-dropdown-button-hover-background": "var(--muted)",

  "--ck-qr-dot-color": "var(--foreground)",
  "--ck-qr-background": "var(--background)",
  "--ck-qr-border-color": "var(--border)",

  "--ck-focus-color": "var(--ring)",
  "--ck-spinner-color": "var(--ring)",
  "--ck-copytoclipboard-stroke": "var(--border)",
  "--ck-recent-badge-color": "var(--muted-foreground)",
  "--ck-recent-badge-background": "var(--secondary)",
  "--ck-recent-badge-border-radius": "32px",
};
export { customeTheme };
