/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { Lock } from "./Lock";
export type { StakingContract } from "./StakingContract";
export type { StakingFactory } from "./StakingFactory";
export type { TokenA } from "./TokenA";
export type { TokenB } from "./TokenB";
export * as factories from "./factories";
export { IERC20__factory } from "./factories/IERC20__factory";
export { Lock__factory } from "./factories/Lock__factory";
export { StakingContract__factory } from "./factories/StakingContract__factory";
export { StakingFactory__factory } from "./factories/StakingFactory__factory";
export { TokenA__factory } from "./factories/TokenA__factory";
export { TokenB__factory } from "./factories/TokenB__factory";
